### ISSUE TITLE
Readme is now out of date - no usable instructions on how to build

### ISSUE THREAD

**Issue by SBoylan-Ircona** [openbmc/sdeventplus#3]
The README file still assumes automake is part of the build process, yet all automake resources have been removed, with no instructions on how to use meson included.

**Comment by mine260309** [comment]
I got the same issue, there is no `bootstrap.sh` at all.

~And when I was using `openbmc-build-scripts/run-unit-test-docker.sh` to run tests in sdbusplus, I got the error while building `sdeventplus` repo:~


~Step 33/93 : RUN curl -L https://github.com/openbmc/sdeventplus/archive/b315a2ab41ab6408a2185162fdd56c836249abdc.tar.gz | tar -xz && cd sdeventplus-* && ./bootstrap.sh && ./configure --prefix=/usr/local --disable-tests --disable-examples && make -j24 && make install~
~/bin/sh: 1: ./bootstrap.sh: not found~

---

I was using an old `openbmc-build-scripts`, updated to latest and it works fine.
But the README is deprecated anyway.

**Comment by wak-google** [comment]
You just need to update your openbmc-build-scripts. I do need to update the README

**Comment by wak-google** [comment]
Fix by 9412219317e8949fd23f5c29e550a57611e0ad3d
